//
//  TSGraphics.m
//  (null)
//
//  Created by Jordan Guggenheim on 7/12/15.
//  Copyright (c) 2015 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "TSGraphics.h"


@implementation TSGraphics

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawBiggerStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// star Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame) + 11.12, CGRectGetMinY(frame) + 9.62);
    CGContextRotateCTM(context, -rotation * M_PI / 180);

    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(0, -9.38)];
    [starPath addLineToPoint: CGPointMake(2.5, -3.26)];
    [starPath addLineToPoint: CGPointMake(9.39, -2.9)];
    [starPath addLineToPoint: CGPointMake(4.04, 1.25)];
    [starPath addLineToPoint: CGPointMake(5.8, 7.58)];
    [starPath addLineToPoint: CGPointMake(0, 4.03)];
    [starPath addLineToPoint: CGPointMake(-5.8, 7.58)];
    [starPath addLineToPoint: CGPointMake(-4.04, 1.25)];
    [starPath addLineToPoint: CGPointMake(-9.39, -2.9)];
    [starPath addLineToPoint: CGPointMake(-2.5, -3.26)];
    [starPath closePath];
    [starColor setFill];
    [starPath fill];

    CGContextRestoreGState(context);
}

+ (void)drawMediumStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// star Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame) + 6.96, CGRectGetMinY(frame) + 6.98);
    CGContextRotateCTM(context, -rotation * M_PI / 180);

    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(0, -7.03)];
    [starPath addLineToPoint: CGPointMake(1.2, -2.07)];
    [starPath addLineToPoint: CGPointMake(6.09, -3.51)];
    [starPath addLineToPoint: CGPointMake(2.39, -0)];
    [starPath addLineToPoint: CGPointMake(6.09, 3.51)];
    [starPath addLineToPoint: CGPointMake(1.2, 2.07)];
    [starPath addLineToPoint: CGPointMake(0, 7.03)];
    [starPath addLineToPoint: CGPointMake(-1.2, 2.07)];
    [starPath addLineToPoint: CGPointMake(-6.09, 3.51)];
    [starPath addLineToPoint: CGPointMake(-2.39, -0)];
    [starPath addLineToPoint: CGPointMake(-6.09, -3.51)];
    [starPath addLineToPoint: CGPointMake(-1.2, -2.07)];
    [starPath closePath];
    [starColor setFill];
    [starPath fill];

    CGContextRestoreGState(context);
}

+ (void)drawLittleStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// star Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame) + 2, CGRectGetMinY(frame) + 2);
    CGContextRotateCTM(context, -rotation * M_PI / 180);

    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(0, -1.5)];
    [starPath addLineToPoint: CGPointMake(0.18, -0.48)];
    [starPath addLineToPoint: CGPointMake(0.99, -1.15)];
    [starPath addLineToPoint: CGPointMake(0.45, -0.25)];
    [starPath addLineToPoint: CGPointMake(1.51, -0.26)];
    [starPath addLineToPoint: CGPointMake(0.51, 0.09)];
    [starPath addLineToPoint: CGPointMake(1.33, 0.75)];
    [starPath addLineToPoint: CGPointMake(0.34, 0.39)];
    [starPath addLineToPoint: CGPointMake(0.53, 1.41)];
    [starPath addLineToPoint: CGPointMake(0, 0.51)];
    [starPath addLineToPoint: CGPointMake(-0.53, 1.41)];
    [starPath addLineToPoint: CGPointMake(-0.34, 0.39)];
    [starPath addLineToPoint: CGPointMake(-1.33, 0.75)];
    [starPath addLineToPoint: CGPointMake(-0.51, 0.09)];
    [starPath addLineToPoint: CGPointMake(-1.51, -0.26)];
    [starPath addLineToPoint: CGPointMake(-0.45, -0.25)];
    [starPath addLineToPoint: CGPointMake(-0.99, -1.15)];
    [starPath addLineToPoint: CGPointMake(-0.18, -0.48)];
    [starPath closePath];
    [starColor setFill];
    [starPath fill];

    CGContextRestoreGState(context);
}

+ (void)drawBigStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// star Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame) + 9.62, CGRectGetMinY(frame) + 8.12);
    CGContextRotateCTM(context, -rotation * M_PI / 180);

    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(0, -7.88)];
    [starPath addLineToPoint: CGPointMake(2.12, -2.74)];
    [starPath addLineToPoint: CGPointMake(7.97, -2.43)];
    [starPath addLineToPoint: CGPointMake(3.42, 1.05)];
    [starPath addLineToPoint: CGPointMake(4.92, 6.37)];
    [starPath addLineToPoint: CGPointMake(0, 3.39)];
    [starPath addLineToPoint: CGPointMake(-4.92, 6.37)];
    [starPath addLineToPoint: CGPointMake(-3.42, 1.05)];
    [starPath addLineToPoint: CGPointMake(-7.97, -2.43)];
    [starPath addLineToPoint: CGPointMake(-2.12, -2.74)];
    [starPath closePath];
    [starColor setFill];
    [starPath fill];

    CGContextRestoreGState(context);
}

+ (void)drawDayNightGradientWithCanvasSize: (CGSize)canvasSize
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* green = [UIColor colorWithRed: 0.58 green: 0.729 blue: 0.396 alpha: 1];
    UIColor* blue = [UIColor colorWithRed: 0.153 green: 0.565 blue: 0.682 alpha: 1];
    UIColor* midnight = [UIColor colorWithRed: 0 green: 0 blue: 0.039 alpha: 1];

    //// Gradient Declarations
    CGFloat gradientLocations[] = {0, 0.5, 1};
    CGGradientRef gradient = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)green.CGColor, (id)blue.CGColor, (id)midnight.CGColor], gradientLocations);

    //// backgroundGradient Drawing
    CGRect backgroundGradientRect = CGRectMake(0, 0, canvasSize.width, canvasSize.height);
    UIBezierPath* backgroundGradientPath = [UIBezierPath bezierPathWithRect: backgroundGradientRect];
    CGContextSaveGState(context);
    [backgroundGradientPath addClip];
    CGContextDrawLinearGradient(context, gradient,
        CGPointMake(CGRectGetMidX(backgroundGradientRect), CGRectGetMaxY(backgroundGradientRect)),
        CGPointMake(CGRectGetMidX(backgroundGradientRect), CGRectGetMinY(backgroundGradientRect)),
        0);
    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(gradient);
    CGColorSpaceRelease(colorSpace);
}

+ (void)drawDayGradientWithCanvasSize: (CGSize)canvasSize
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* green = [UIColor colorWithRed: 0.58 green: 0.729 blue: 0.396 alpha: 1];
    UIColor* blue = [UIColor colorWithRed: 0.153 green: 0.565 blue: 0.682 alpha: 1];

    //// Gradient Declarations
    CGFloat dayLocations[] = {0, 0.5, 1};
    CGGradientRef day = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)green.CGColor, (id)[green blendedColorWithFraction: 0.5 ofColor: blue].CGColor, (id)blue.CGColor], dayLocations);

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(0, 0, canvasSize.width, canvasSize.height);
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: rectangleRect];
    CGContextSaveGState(context);
    [rectanglePath addClip];
    CGContextDrawLinearGradient(context, day,
        CGPointMake(CGRectGetMidX(rectangleRect), CGRectGetMaxY(rectangleRect)),
        CGPointMake(CGRectGetMidX(rectangleRect), CGRectGetMinY(rectangleRect)),
        0);
    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(day);
    CGColorSpaceRelease(colorSpace);
}

+ (void)drawNightGradientWithCanvasSize: (CGSize)canvasSize
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* blue = [UIColor colorWithRed: 0.153 green: 0.565 blue: 0.682 alpha: 1];
    UIColor* midnight = [UIColor colorWithRed: 0 green: 0 blue: 0.039 alpha: 1];

    //// Gradient Declarations
    CGFloat nIghtLocations[] = {0, 0.76};
    CGGradientRef nIght = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)blue.CGColor, (id)midnight.CGColor], nIghtLocations);

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(0, 0, canvasSize.width, canvasSize.height);
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: rectangleRect];
    CGContextSaveGState(context);
    [rectanglePath addClip];
    CGContextDrawLinearGradient(context, nIght,
        CGPointMake(CGRectGetMidX(rectangleRect), CGRectGetMaxY(rectangleRect)),
        CGPointMake(CGRectGetMidX(rectangleRect), CGRectGetMinY(rectangleRect)),
        0);
    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(nIght);
    CGColorSpaceRelease(colorSpace);
}

+ (void)drawSheepCloudsWithAlpha: (CGFloat)alpha
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* fillColor2 = [UIColor colorWithRed: 0.951 green: 0.951 blue: 0.951 alpha: 1];
    UIColor* fillColor3 = [UIColor colorWithRed: 0.943 green: 0.817 blue: 0.697 alpha: 1];
    UIColor* fillColor4 = [UIColor colorWithRed: 0.271 green: 0.271 blue: 0.267 alpha: 1];

    //// sheepGroup
    {
        CGContextSaveGState(context);
        CGContextSetAlpha(context, alpha);
        CGContextBeginTransparencyLayer(context, NULL);


        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(108.37, 115.13)];
        [bezierPath addCurveToPoint: CGPointMake(96.01, 115.04) controlPoint1: CGPointMake(104.39, 113.45) controlPoint2: CGPointMake(100.05, 113.78)];
        [bezierPath addCurveToPoint: CGPointMake(87.62, 102.47) controlPoint1: CGPointMake(95.53, 109.77) controlPoint2: CGPointMake(92.57, 104.84)];
        [bezierPath addCurveToPoint: CGPointMake(71.57, 104.5) controlPoint1: CGPointMake(82.39, 99.97) controlPoint2: CGPointMake(76.02, 100.94)];
        [bezierPath addCurveToPoint: CGPointMake(56.13, 96.66) controlPoint1: CGPointMake(67.91, 99.75) controlPoint2: CGPointMake(62.19, 96.69)];
        [bezierPath addCurveToPoint: CGPointMake(39.52, 105.84) controlPoint1: CGPointMake(49.43, 96.62) controlPoint2: CGPointMake(43.14, 100.28)];
        [bezierPath addCurveToPoint: CGPointMake(27.11, 102.42) controlPoint1: CGPointMake(36.91, 101.78) controlPoint2: CGPointMake(31.65, 100.07)];
        [bezierPath addCurveToPoint: CGPointMake(21.72, 114.18) controlPoint1: CGPointMake(22.75, 104.68) controlPoint2: CGPointMake(20.86, 109.61)];
        [bezierPath addCurveToPoint: CGPointMake(15.07, 121.71) controlPoint1: CGPointMake(18.43, 115.48) controlPoint2: CGPointMake(15.47, 118)];
        [bezierPath addCurveToPoint: CGPointMake(17.46, 128.15) controlPoint1: CGPointMake(14.81, 124.13) controlPoint2: CGPointMake(15.76, 126.57)];
        [bezierPath addCurveToPoint: CGPointMake(12.49, 150.95) controlPoint1: CGPointMake(11.48, 134.03) controlPoint2: CGPointMake(8.9, 142.82)];
        [bezierPath addCurveToPoint: CGPointMake(33.98, 160.23) controlPoint1: CGPointMake(16.16, 159.27) controlPoint2: CGPointMake(25.75, 163.42)];
        [bezierPath addCurveToPoint: CGPointMake(42.06, 164.45) controlPoint1: CGPointMake(35.45, 163.06) controlPoint2: CGPointMake(38.79, 164.88)];
        [bezierPath addCurveToPoint: CGPointMake(49.23, 158.21) controlPoint1: CGPointMake(45.6, 163.99) controlPoint2: CGPointMake(48.02, 161.36)];
        [bezierPath addCurveToPoint: CGPointMake(59.24, 156.4) controlPoint1: CGPointMake(52.63, 159.65) controlPoint2: CGPointMake(56.61, 158.88)];
        [bezierPath addCurveToPoint: CGPointMake(76.1, 165.27) controlPoint1: CGPointMake(62.72, 162.22) controlPoint2: CGPointMake(69.12, 166.33)];
        [bezierPath addCurveToPoint: CGPointMake(88.57, 152.79) controlPoint1: CGPointMake(82.46, 164.31) controlPoint2: CGPointMake(87.58, 158.96)];
        [bezierPath addCurveToPoint: CGPointMake(94.85, 151.92) controlPoint1: CGPointMake(90.61, 153.3) controlPoint2: CGPointMake(92.85, 153.05)];
        [bezierPath addCurveToPoint: CGPointMake(99.45, 144.33) controlPoint1: CGPointMake(97.68, 150.32) controlPoint2: CGPointMake(99.11, 147.41)];
        [bezierPath addCurveToPoint: CGPointMake(108.53, 141.84) controlPoint1: CGPointMake(102.54, 144.84) controlPoint2: CGPointMake(105.9, 143.75)];
        [bezierPath addCurveToPoint: CGPointMake(116.32, 127.49) controlPoint1: CGPointMake(113.05, 138.55) controlPoint2: CGPointMake(116.39, 133.22)];
        [bezierPath addCurveToPoint: CGPointMake(108.37, 115.13) controlPoint1: CGPointMake(116.25, 122.18) controlPoint2: CGPointMake(113.3, 117.2)];
        [bezierPath closePath];
        [fillColor2 setFill];
        [bezierPath fill];


        //// Group 2
        {
            //// Bezier 2 Drawing
            UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
            [bezier2Path moveToPoint: CGPointMake(115.97, 66.48)];
            [bezier2Path addCurveToPoint: CGPointMake(115.61, 66.46) controlPoint1: CGPointMake(115.86, 66.44) controlPoint2: CGPointMake(115.73, 66.43)];
            [bezier2Path addCurveToPoint: CGPointMake(114.62, 67.25) controlPoint1: CGPointMake(115.19, 66.5) controlPoint2: CGPointMake(114.79, 66.74)];
            [bezier2Path addCurveToPoint: CGPointMake(114.46, 67.68) controlPoint1: CGPointMake(114.57, 67.39) controlPoint2: CGPointMake(114.51, 67.54)];
            [bezier2Path addCurveToPoint: CGPointMake(110.59, 74.74) controlPoint1: CGPointMake(112.81, 69.78) controlPoint2: CGPointMake(111.66, 72.29)];
            [bezier2Path addCurveToPoint: CGPointMake(109.62, 80.18) controlPoint1: CGPointMake(110.06, 75.97) controlPoint2: CGPointMake(108.08, 79.04)];
            [bezier2Path addCurveToPoint: CGPointMake(112.96, 77.25) controlPoint1: CGPointMake(111.4, 81.5) controlPoint2: CGPointMake(112.45, 78.33)];
            [bezier2Path addCurveToPoint: CGPointMake(116.8, 67.86) controlPoint1: CGPointMake(114.4, 74.19) controlPoint2: CGPointMake(115.65, 71.05)];
            [bezier2Path addCurveToPoint: CGPointMake(115.97, 66.48) controlPoint1: CGPointMake(117.06, 67.12) controlPoint2: CGPointMake(116.57, 66.6)];
            [bezier2Path closePath];
            [fillColor3 setFill];
            [bezier2Path fill];


            //// Bezier 3 Drawing
            UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
            [bezier3Path moveToPoint: CGPointMake(123.03, 69.01)];
            [bezier3Path addCurveToPoint: CGPointMake(122.44, 68.99) controlPoint1: CGPointMake(122.87, 68.9) controlPoint2: CGPointMake(122.65, 68.88)];
            [bezier3Path addCurveToPoint: CGPointMake(121.95, 69.43) controlPoint1: CGPointMake(122.26, 69.06) controlPoint2: CGPointMake(122.09, 69.2)];
            [bezier3Path addCurveToPoint: CGPointMake(118.63, 75.8) controlPoint1: CGPointMake(120.36, 71.13) controlPoint2: CGPointMake(119.49, 73.69)];
            [bezier3Path addCurveToPoint: CGPointMake(116.49, 83.36) controlPoint1: CGPointMake(117.63, 78.25) controlPoint2: CGPointMake(116.67, 80.69)];
            [bezier3Path addCurveToPoint: CGPointMake(118.23, 84.38) controlPoint1: CGPointMake(116.43, 84.24) controlPoint2: CGPointMake(117.52, 84.85)];
            [bezier3Path addCurveToPoint: CGPointMake(120.98, 78.77) controlPoint1: CGPointMake(119.98, 83.22) controlPoint2: CGPointMake(120.34, 80.65)];
            [bezier3Path addCurveToPoint: CGPointMake(123.76, 70.25) controlPoint1: CGPointMake(121.93, 76.03) controlPoint2: CGPointMake(123.3, 73.12)];
            [bezier3Path addCurveToPoint: CGPointMake(123.03, 69.01) controlPoint1: CGPointMake(123.85, 69.67) controlPoint2: CGPointMake(123.48, 69.17)];
            [bezier3Path closePath];
            [fillColor3 setFill];
            [bezier3Path fill];


            //// Bezier 4 Drawing
            UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
            [bezier4Path moveToPoint: CGPointMake(167.7, 79.3)];
            [bezier4Path addCurveToPoint: CGPointMake(162.93, 74.87) controlPoint1: CGPointMake(166.11, 77.82) controlPoint2: CGPointMake(164.52, 76.34)];
            [bezier4Path addCurveToPoint: CGPointMake(160.69, 72.78) controlPoint1: CGPointMake(162.19, 74.17) controlPoint2: CGPointMake(161.44, 73.48)];
            [bezier4Path addCurveToPoint: CGPointMake(158.41, 70.74) controlPoint1: CGPointMake(160.07, 72.2) controlPoint2: CGPointMake(158.96, 71.48)];
            [bezier4Path addCurveToPoint: CGPointMake(157.35, 69.91) controlPoint1: CGPointMake(158.27, 70.27) controlPoint2: CGPointMake(157.86, 69.92)];
            [bezier4Path addCurveToPoint: CGPointMake(157.26, 69.91) controlPoint1: CGPointMake(157.32, 69.91) controlPoint2: CGPointMake(157.29, 69.91)];
            [bezier4Path addCurveToPoint: CGPointMake(156.3, 70.47) controlPoint1: CGPointMake(156.87, 69.9) controlPoint2: CGPointMake(156.51, 70.14)];
            [bezier4Path addCurveToPoint: CGPointMake(156.21, 71.51) controlPoint1: CGPointMake(156.05, 70.71) controlPoint2: CGPointMake(155.96, 71.12)];
            [bezier4Path addCurveToPoint: CGPointMake(158.52, 74.17) controlPoint1: CGPointMake(156.57, 72.47) controlPoint2: CGPointMake(157.53, 73.36)];
            [bezier4Path addCurveToPoint: CGPointMake(166.07, 80.97) controlPoint1: CGPointMake(160.84, 76.65) controlPoint2: CGPointMake(163.41, 78.9)];
            [bezier4Path addLineToPoint: CGPointMake(166.07, 80.97)];
            [bezier4Path addLineToPoint: CGPointMake(166.07, 80.97)];
            [bezier4Path addCurveToPoint: CGPointMake(166.3, 81.16) controlPoint1: CGPointMake(166.15, 81.03) controlPoint2: CGPointMake(166.22, 81.1)];
            [bezier4Path addCurveToPoint: CGPointMake(167.7, 79.3) controlPoint1: CGPointMake(167.35, 81.97) controlPoint2: CGPointMake(168.66, 80.2)];
            [bezier4Path closePath];
            [fillColor3 setFill];
            [bezier4Path fill];


            //// Bezier 5 Drawing
            UIBezierPath* bezier5Path = UIBezierPath.bezierPath;
            [bezier5Path moveToPoint: CGPointMake(172.04, 74.53)];
            [bezier5Path addCurveToPoint: CGPointMake(161.7, 66.07) controlPoint1: CGPointMake(168.59, 71.71) controlPoint2: CGPointMake(165.15, 68.89)];
            [bezier5Path addCurveToPoint: CGPointMake(160.74, 65.81) controlPoint1: CGPointMake(161.4, 65.82) controlPoint2: CGPointMake(161.05, 65.76)];
            [bezier5Path addCurveToPoint: CGPointMake(160.67, 65.77) controlPoint1: CGPointMake(160.72, 65.8) controlPoint2: CGPointMake(160.69, 65.79)];
            [bezier5Path addCurveToPoint: CGPointMake(159.59, 66.88) controlPoint1: CGPointMake(160.02, 65.45) controlPoint2: CGPointMake(159.12, 66.16)];
            [bezier5Path addCurveToPoint: CGPointMake(159.66, 66.98) controlPoint1: CGPointMake(159.61, 66.92) controlPoint2: CGPointMake(159.64, 66.95)];
            [bezier5Path addCurveToPoint: CGPointMake(160.06, 67.76) controlPoint1: CGPointMake(159.66, 67.25) controlPoint2: CGPointMake(159.78, 67.53)];
            [bezier5Path addCurveToPoint: CGPointMake(160.66, 68.24) controlPoint1: CGPointMake(160.26, 67.92) controlPoint2: CGPointMake(160.46, 68.08)];
            [bezier5Path addCurveToPoint: CGPointMake(164.82, 71.9) controlPoint1: CGPointMake(161.9, 69.61) controlPoint2: CGPointMake(163.45, 70.76)];
            [bezier5Path addCurveToPoint: CGPointMake(170.64, 76.39) controlPoint1: CGPointMake(166.71, 73.46) controlPoint2: CGPointMake(168.67, 74.94)];
            [bezier5Path addCurveToPoint: CGPointMake(172.04, 74.53) controlPoint1: CGPointMake(171.69, 77.16) controlPoint2: CGPointMake(173.07, 75.37)];
            [bezier5Path closePath];
            [fillColor3 setFill];
            [bezier5Path fill];


            //// Bezier 6 Drawing
            UIBezierPath* bezier6Path = UIBezierPath.bezierPath;
            [bezier6Path moveToPoint: CGPointMake(169.05, 48.22)];
            [bezier6Path addCurveToPoint: CGPointMake(160.84, 39.39) controlPoint1: CGPointMake(168.57, 43.56) controlPoint2: CGPointMake(165.04, 39.76)];
            [bezier6Path addCurveToPoint: CGPointMake(156.86, 27.41) controlPoint1: CGPointMake(162.09, 35.1) controlPoint2: CGPointMake(160.64, 30.04)];
            [bezier6Path addCurveToPoint: CGPointMake(142.94, 29.51) controlPoint1: CGPointMake(152.47, 24.37) controlPoint2: CGPointMake(146.43, 25.73)];
            [bezier6Path addCurveToPoint: CGPointMake(134.44, 25.69) controlPoint1: CGPointMake(140.97, 26.94) controlPoint2: CGPointMake(137.69, 25.47)];
            [bezier6Path addCurveToPoint: CGPointMake(125.8, 30.57) controlPoint1: CGPointMake(130.95, 25.93) controlPoint2: CGPointMake(127.99, 27.9)];
            [bezier6Path addCurveToPoint: CGPointMake(124.12, 26.51) controlPoint1: CGPointMake(125.81, 29.08) controlPoint2: CGPointMake(125.33, 27.64)];
            [bezier6Path addCurveToPoint: CGPointMake(118.78, 25.47) controlPoint1: CGPointMake(122.67, 25.16) controlPoint2: CGPointMake(120.54, 24.77)];
            [bezier6Path addCurveToPoint: CGPointMake(110.8, 23.12) controlPoint1: CGPointMake(117, 23.03) controlPoint2: CGPointMake(113.71, 21.9)];
            [bezier6Path addCurveToPoint: CGPointMake(106.54, 31.3) controlPoint1: CGPointMake(107.65, 24.43) controlPoint2: CGPointMake(106.15, 27.99)];
            [bezier6Path addCurveToPoint: CGPointMake(102.56, 38.87) controlPoint1: CGPointMake(103.64, 32.23) controlPoint2: CGPointMake(101.72, 35.76)];
            [bezier6Path addCurveToPoint: CGPointMake(109.57, 43.63) controlPoint1: CGPointMake(103.42, 42.04) controlPoint2: CGPointMake(106.54, 43.68)];
            [bezier6Path addCurveToPoint: CGPointMake(113.88, 50.92) controlPoint1: CGPointMake(109.31, 46.8) controlPoint2: CGPointMake(111.12, 49.71)];
            [bezier6Path addCurveToPoint: CGPointMake(113.49, 66.36) controlPoint1: CGPointMake(110.66, 55.16) controlPoint2: CGPointMake(110.66, 61.84)];
            [bezier6Path addCurveToPoint: CGPointMake(127.24, 69.6) controlPoint1: CGPointMake(116.47, 71.12) controlPoint2: CGPointMake(123, 72.9)];
            [bezier6Path addCurveToPoint: CGPointMake(132.28, 73.96) controlPoint1: CGPointMake(128.3, 71.66) controlPoint2: CGPointMake(130.02, 73.34)];
            [bezier6Path addCurveToPoint: CGPointMake(138.54, 72.52) controlPoint1: CGPointMake(134.47, 74.55) controlPoint2: CGPointMake(136.85, 73.97)];
            [bezier6Path addCurveToPoint: CGPointMake(155.23, 75.07) controlPoint1: CGPointMake(142.66, 77.29) controlPoint2: CGPointMake(149.66, 78.17)];
            [bezier6Path addCurveToPoint: CGPointMake(161.91, 60.7) controlPoint1: CGPointMake(159.99, 72.42) controlPoint2: CGPointMake(163.73, 66.13)];
            [bezier6Path addCurveToPoint: CGPointMake(169.05, 48.22) controlPoint1: CGPointMake(166.72, 59.13) controlPoint2: CGPointMake(169.59, 53.33)];
            [bezier6Path closePath];
            [fillColor2 setFill];
            [bezier6Path fill];


            //// Bezier 7 Drawing
            UIBezierPath* bezier7Path = UIBezierPath.bezierPath;
            [bezier7Path moveToPoint: CGPointMake(114.94, 44.04)];
            [bezier7Path addCurveToPoint: CGPointMake(112.94, 41.68) controlPoint1: CGPointMake(113.6, 44.03) controlPoint2: CGPointMake(112.83, 42.99)];
            [bezier7Path addCurveToPoint: CGPointMake(112.92, 41.5) controlPoint1: CGPointMake(112.94, 41.62) controlPoint2: CGPointMake(112.94, 41.56)];
            [bezier7Path addCurveToPoint: CGPointMake(113.18, 40.99) controlPoint1: CGPointMake(113.05, 41.36) controlPoint2: CGPointMake(113.15, 41.19)];
            [bezier7Path addCurveToPoint: CGPointMake(113.18, 40.72) controlPoint1: CGPointMake(113.2, 40.89) controlPoint2: CGPointMake(113.19, 40.8)];
            [bezier7Path addCurveToPoint: CGPointMake(113.22, 40.65) controlPoint1: CGPointMake(113.19, 40.69) controlPoint2: CGPointMake(113.2, 40.67)];
            [bezier7Path addCurveToPoint: CGPointMake(112.57, 39.98) controlPoint1: CGPointMake(113.46, 40.26) controlPoint2: CGPointMake(112.95, 39.68)];
            [bezier7Path addCurveToPoint: CGPointMake(112.36, 40.17) controlPoint1: CGPointMake(112.49, 40.04) controlPoint2: CGPointMake(112.43, 40.11)];
            [bezier7Path addCurveToPoint: CGPointMake(110.88, 40.29) controlPoint1: CGPointMake(111.87, 40.2) controlPoint2: CGPointMake(111.38, 40.52)];
            [bezier7Path addCurveToPoint: CGPointMake(110.3, 39.01) controlPoint1: CGPointMake(110.42, 40.08) controlPoint2: CGPointMake(110.15, 39.49)];
            [bezier7Path addCurveToPoint: CGPointMake(109.7, 38.32) controlPoint1: CGPointMake(110.43, 38.55) controlPoint2: CGPointMake(110.06, 38.28)];
            [bezier7Path addCurveToPoint: CGPointMake(109.07, 38.35) controlPoint1: CGPointMake(109.51, 38.23) controlPoint2: CGPointMake(109.3, 38.23)];
            [bezier7Path addCurveToPoint: CGPointMake(107.24, 39.67) controlPoint1: CGPointMake(108.39, 38.7) controlPoint2: CGPointMake(108.26, 39.91)];
            [bezier7Path addCurveToPoint: CGPointMake(106.27, 37.8) controlPoint1: CGPointMake(106.47, 39.49) controlPoint2: CGPointMake(106.28, 38.47)];
            [bezier7Path addCurveToPoint: CGPointMake(105.45, 37.35) controlPoint1: CGPointMake(106.27, 37.37) controlPoint2: CGPointMake(105.78, 37.11)];
            [bezier7Path addCurveToPoint: CGPointMake(104.81, 37.62) controlPoint1: CGPointMake(105.21, 37.32) controlPoint2: CGPointMake(104.96, 37.42)];
            [bezier7Path addCurveToPoint: CGPointMake(104, 51.65) controlPoint1: CGPointMake(100.95, 40.28) controlPoint2: CGPointMake(99.77, 48.86)];
            [bezier7Path addCurveToPoint: CGPointMake(115.71, 45.07) controlPoint1: CGPointMake(108.64, 54.71) controlPoint2: CGPointMake(114.4, 49.43)];
            [bezier7Path addCurveToPoint: CGPointMake(114.94, 44.04) controlPoint1: CGPointMake(115.87, 44.56) controlPoint2: CGPointMake(115.45, 44.04)];
            [bezier7Path closePath];
            [fillColor3 setFill];
            [bezier7Path fill];


            //// Bezier 8 Drawing
            UIBezierPath* bezier8Path = UIBezierPath.bezierPath;
            [bezier8Path moveToPoint: CGPointMake(120.59, 33.27)];
            [bezier8Path addCurveToPoint: CGPointMake(114.76, 34.97) controlPoint1: CGPointMake(118.47, 32.86) controlPoint2: CGPointMake(116.37, 33.53)];
            [bezier8Path addCurveToPoint: CGPointMake(114.61, 35.78) controlPoint1: CGPointMake(114.51, 35.19) controlPoint2: CGPointMake(114.49, 35.51)];
            [bezier8Path addCurveToPoint: CGPointMake(114.68, 36.01) controlPoint1: CGPointMake(114.61, 35.86) controlPoint2: CGPointMake(114.62, 35.94)];
            [bezier8Path addCurveToPoint: CGPointMake(120.23, 39.26) controlPoint1: CGPointMake(115.98, 37.75) controlPoint2: CGPointMake(118.06, 39.09)];
            [bezier8Path addCurveToPoint: CGPointMake(123.98, 36.56) controlPoint1: CGPointMake(121.95, 39.39) controlPoint2: CGPointMake(123.76, 38.48)];
            [bezier8Path addCurveToPoint: CGPointMake(120.59, 33.27) controlPoint1: CGPointMake(124.21, 34.58) controlPoint2: CGPointMake(122.19, 33.58)];
            [bezier8Path closePath];
            [fillColor3 setFill];
            [bezier8Path fill];


            //// Bezier 9 Drawing
            UIBezierPath* bezier9Path = UIBezierPath.bezierPath;
            [bezier9Path moveToPoint: CGPointMake(107.03, 41.44)];
            [bezier9Path addCurveToPoint: CGPointMake(105.92, 40.62) controlPoint1: CGPointMake(106.85, 40.95) controlPoint2: CGPointMake(106.43, 40.65)];
            [bezier9Path addCurveToPoint: CGPointMake(104.93, 42.59) controlPoint1: CGPointMake(104.91, 40.56) controlPoint2: CGPointMake(104.07, 41.79)];
            [bezier9Path addCurveToPoint: CGPointMake(105.34, 42.27) controlPoint1: CGPointMake(105.13, 42.79) controlPoint2: CGPointMake(105.51, 42.53)];
            [bezier9Path addCurveToPoint: CGPointMake(105.98, 41.1) controlPoint1: CGPointMake(105, 41.76) controlPoint2: CGPointMake(105.28, 40.89)];
            [bezier9Path addCurveToPoint: CGPointMake(106.53, 41.72) controlPoint1: CGPointMake(106.26, 41.18) controlPoint2: CGPointMake(106.47, 41.43)];
            [bezier9Path addCurveToPoint: CGPointMake(106.43, 42.6) controlPoint1: CGPointMake(106.58, 42.04) controlPoint2: CGPointMake(106.35, 42.3)];
            [bezier9Path addCurveToPoint: CGPointMake(106.73, 42.78) controlPoint1: CGPointMake(106.46, 42.74) controlPoint2: CGPointMake(106.61, 42.82)];
            [bezier9Path addCurveToPoint: CGPointMake(107.03, 41.44) controlPoint1: CGPointMake(107.22, 42.63) controlPoint2: CGPointMake(107.18, 41.83)];
            [bezier9Path closePath];
            [fillColor4 setFill];
            [bezier9Path fill];
        }


        //// Bezier 10 Drawing
        UIBezierPath* bezier10Path = UIBezierPath.bezierPath;
        [bezier10Path moveToPoint: CGPointMake(428, 17.4)];
        [bezier10Path addCurveToPoint: CGPointMake(416.44, 17.32) controlPoint1: CGPointMake(424.27, 15.88) controlPoint2: CGPointMake(420.22, 16.18)];
        [bezier10Path addCurveToPoint: CGPointMake(408.59, 5.92) controlPoint1: CGPointMake(415.99, 12.54) controlPoint2: CGPointMake(413.22, 8.06)];
        [bezier10Path addCurveToPoint: CGPointMake(393.59, 7.76) controlPoint1: CGPointMake(403.71, 3.65) controlPoint2: CGPointMake(397.74, 4.53)];
        [bezier10Path addCurveToPoint: CGPointMake(379.15, 0.65) controlPoint1: CGPointMake(390.16, 3.45) controlPoint2: CGPointMake(384.82, 0.68)];
        [bezier10Path addCurveToPoint: CGPointMake(363.62, 8.97) controlPoint1: CGPointMake(372.89, 0.61) controlPoint2: CGPointMake(367.01, 3.93)];
        [bezier10Path addCurveToPoint: CGPointMake(352.02, 5.88) controlPoint1: CGPointMake(361.18, 5.3) controlPoint2: CGPointMake(356.26, 3.74)];
        [bezier10Path addCurveToPoint: CGPointMake(346.98, 16.54) controlPoint1: CGPointMake(347.94, 7.92) controlPoint2: CGPointMake(346.17, 12.39)];
        [bezier10Path addCurveToPoint: CGPointMake(340.76, 23.37) controlPoint1: CGPointMake(343.9, 17.72) controlPoint2: CGPointMake(341.13, 20)];
        [bezier10Path addCurveToPoint: CGPointMake(343, 29.2) controlPoint1: CGPointMake(340.51, 25.56) controlPoint2: CGPointMake(341.41, 27.77)];
        [bezier10Path addCurveToPoint: CGPointMake(338.34, 49.88) controlPoint1: CGPointMake(337.41, 34.54) controlPoint2: CGPointMake(334.99, 42.51)];
        [bezier10Path addCurveToPoint: CGPointMake(358.44, 58.3) controlPoint1: CGPointMake(341.78, 57.43) controlPoint2: CGPointMake(350.74, 61.19)];
        [bezier10Path addCurveToPoint: CGPointMake(365.99, 62.13) controlPoint1: CGPointMake(359.81, 60.87) controlPoint2: CGPointMake(362.93, 62.52)];
        [bezier10Path addCurveToPoint: CGPointMake(372.7, 56.47) controlPoint1: CGPointMake(369.3, 61.71) controlPoint2: CGPointMake(371.56, 59.32)];
        [bezier10Path addCurveToPoint: CGPointMake(382.06, 54.82) controlPoint1: CGPointMake(375.88, 57.77) controlPoint2: CGPointMake(379.6, 57.07)];
        [bezier10Path addCurveToPoint: CGPointMake(397.82, 62.87) controlPoint1: CGPointMake(385.32, 60.11) controlPoint2: CGPointMake(391.3, 63.83)];
        [bezier10Path addCurveToPoint: CGPointMake(409.48, 51.56) controlPoint1: CGPointMake(403.77, 62) controlPoint2: CGPointMake(408.56, 57.15)];
        [bezier10Path addCurveToPoint: CGPointMake(415.35, 50.76) controlPoint1: CGPointMake(411.39, 52.01) controlPoint2: CGPointMake(413.48, 51.78)];
        [bezier10Path addCurveToPoint: CGPointMake(419.66, 43.88) controlPoint1: CGPointMake(418, 49.31) controlPoint2: CGPointMake(419.34, 46.67)];
        [bezier10Path addCurveToPoint: CGPointMake(428.14, 41.62) controlPoint1: CGPointMake(422.54, 44.34) controlPoint2: CGPointMake(425.69, 43.36)];
        [bezier10Path addCurveToPoint: CGPointMake(435.43, 28.61) controlPoint1: CGPointMake(432.37, 38.63) controlPoint2: CGPointMake(435.49, 33.8)];
        [bezier10Path addCurveToPoint: CGPointMake(428, 17.4) controlPoint1: CGPointMake(435.37, 23.79) controlPoint2: CGPointMake(432.61, 19.28)];
        [bezier10Path closePath];
        [fillColor2 setFill];
        [bezier10Path fill];


        //// Group
        {
            //// Bezier 11 Drawing
            UIBezierPath* bezier11Path = UIBezierPath.bezierPath;
            [bezier11Path moveToPoint: CGPointMake(348.96, 159.6)];
            [bezier11Path addCurveToPoint: CGPointMake(348.42, 159.56) controlPoint1: CGPointMake(348.79, 159.53) controlPoint2: CGPointMake(348.6, 159.51)];
            [bezier11Path addCurveToPoint: CGPointMake(346.97, 160.68) controlPoint1: CGPointMake(347.82, 159.62) controlPoint2: CGPointMake(347.23, 159.96)];
            [bezier11Path addCurveToPoint: CGPointMake(346.74, 161.3) controlPoint1: CGPointMake(346.9, 160.88) controlPoint2: CGPointMake(346.82, 161.09)];
            [bezier11Path addCurveToPoint: CGPointMake(341.08, 171.32) controlPoint1: CGPointMake(344.33, 164.28) controlPoint2: CGPointMake(342.64, 167.84)];
            [bezier11Path addCurveToPoint: CGPointMake(339.66, 179.04) controlPoint1: CGPointMake(340.3, 173.06) controlPoint2: CGPointMake(337.4, 177.42)];
            [bezier11Path addCurveToPoint: CGPointMake(344.54, 174.89) controlPoint1: CGPointMake(342.26, 180.91) controlPoint2: CGPointMake(343.8, 176.42)];
            [bezier11Path addCurveToPoint: CGPointMake(350.16, 161.55) controlPoint1: CGPointMake(346.65, 170.54) controlPoint2: CGPointMake(348.49, 166.08)];
            [bezier11Path addCurveToPoint: CGPointMake(348.96, 159.6) controlPoint1: CGPointMake(350.55, 160.5) controlPoint2: CGPointMake(349.83, 159.76)];
            [bezier11Path closePath];
            [fillColor3 setFill];
            [bezier11Path fill];


            //// Bezier 12 Drawing
            UIBezierPath* bezier12Path = UIBezierPath.bezierPath;
            [bezier12Path moveToPoint: CGPointMake(359.3, 163.18)];
            [bezier12Path addCurveToPoint: CGPointMake(358.44, 163.16) controlPoint1: CGPointMake(359.05, 163.03) controlPoint2: CGPointMake(358.74, 163)];
            [bezier12Path addCurveToPoint: CGPointMake(357.72, 163.78) controlPoint1: CGPointMake(358.16, 163.25) controlPoint2: CGPointMake(357.91, 163.45)];
            [bezier12Path addCurveToPoint: CGPointMake(352.85, 172.83) controlPoint1: CGPointMake(355.38, 166.19) controlPoint2: CGPointMake(354.11, 169.83)];
            [bezier12Path addCurveToPoint: CGPointMake(349.72, 183.55) controlPoint1: CGPointMake(351.38, 176.3) controlPoint2: CGPointMake(349.99, 179.76)];
            [bezier12Path addCurveToPoint: CGPointMake(352.27, 185.01) controlPoint1: CGPointMake(349.63, 184.81) controlPoint2: CGPointMake(351.23, 185.67)];
            [bezier12Path addCurveToPoint: CGPointMake(356.3, 177.05) controlPoint1: CGPointMake(354.82, 183.36) controlPoint2: CGPointMake(355.35, 179.71)];
            [bezier12Path addCurveToPoint: CGPointMake(360.36, 164.94) controlPoint1: CGPointMake(357.69, 173.15) controlPoint2: CGPointMake(359.69, 169.02)];
            [bezier12Path addCurveToPoint: CGPointMake(359.3, 163.18) controlPoint1: CGPointMake(360.49, 164.12) controlPoint2: CGPointMake(359.96, 163.41)];
            [bezier12Path closePath];
            [fillColor3 setFill];
            [bezier12Path fill];


            //// Bezier 13 Drawing
            UIBezierPath* bezier13Path = UIBezierPath.bezierPath;
            [bezier13Path moveToPoint: CGPointMake(424.7, 177.79)];
            [bezier13Path addCurveToPoint: CGPointMake(417.73, 171.5) controlPoint1: CGPointMake(422.38, 175.69) controlPoint2: CGPointMake(420.05, 173.6)];
            [bezier13Path addCurveToPoint: CGPointMake(414.44, 168.54) controlPoint1: CGPointMake(416.63, 170.51) controlPoint2: CGPointMake(415.54, 169.52)];
            [bezier13Path addCurveToPoint: CGPointMake(411.11, 165.64) controlPoint1: CGPointMake(413.52, 167.71) controlPoint2: CGPointMake(411.91, 166.69)];
            [bezier13Path addCurveToPoint: CGPointMake(409.54, 164.46) controlPoint1: CGPointMake(410.89, 164.97) controlPoint2: CGPointMake(410.3, 164.48)];
            [bezier13Path addCurveToPoint: CGPointMake(409.42, 164.46) controlPoint1: CGPointMake(409.5, 164.46) controlPoint2: CGPointMake(409.46, 164.46)];
            [bezier13Path addCurveToPoint: CGPointMake(408.02, 165.25) controlPoint1: CGPointMake(408.85, 164.45) controlPoint2: CGPointMake(408.32, 164.78)];
            [bezier13Path addCurveToPoint: CGPointMake(407.88, 166.73) controlPoint1: CGPointMake(407.65, 165.6) controlPoint2: CGPointMake(407.51, 166.18)];
            [bezier13Path addCurveToPoint: CGPointMake(411.26, 170.51) controlPoint1: CGPointMake(408.41, 168.09) controlPoint2: CGPointMake(409.82, 169.36)];
            [bezier13Path addCurveToPoint: CGPointMake(422.31, 180.17) controlPoint1: CGPointMake(414.66, 174.03) controlPoint2: CGPointMake(418.42, 177.22)];
            [bezier13Path addLineToPoint: CGPointMake(422.31, 180.17)];
            [bezier13Path addLineToPoint: CGPointMake(422.31, 180.17)];
            [bezier13Path addCurveToPoint: CGPointMake(422.66, 180.43) controlPoint1: CGPointMake(422.43, 180.26) controlPoint2: CGPointMake(422.54, 180.35)];
            [bezier13Path addCurveToPoint: CGPointMake(424.7, 177.79) controlPoint1: CGPointMake(424.19, 181.59) controlPoint2: CGPointMake(426.11, 179.06)];
            [bezier13Path closePath];
            [fillColor3 setFill];
            [bezier13Path fill];


            //// Bezier 14 Drawing
            UIBezierPath* bezier14Path = UIBezierPath.bezierPath;
            [bezier14Path moveToPoint: CGPointMake(431.06, 171.02)];
            [bezier14Path addCurveToPoint: CGPointMake(415.92, 159.01) controlPoint1: CGPointMake(426.01, 167.02) controlPoint2: CGPointMake(420.97, 163.01)];
            [bezier14Path addCurveToPoint: CGPointMake(414.51, 158.65) controlPoint1: CGPointMake(415.47, 158.65) controlPoint2: CGPointMake(414.97, 158.57)];
            [bezier14Path addCurveToPoint: CGPointMake(414.41, 158.59) controlPoint1: CGPointMake(414.47, 158.63) controlPoint2: CGPointMake(414.44, 158.61)];
            [bezier14Path addCurveToPoint: CGPointMake(412.83, 160.16) controlPoint1: CGPointMake(413.45, 158.12) controlPoint2: CGPointMake(412.14, 159.13)];
            [bezier14Path addCurveToPoint: CGPointMake(412.94, 160.3) controlPoint1: CGPointMake(412.86, 160.21) controlPoint2: CGPointMake(412.9, 160.25)];
            [bezier14Path addCurveToPoint: CGPointMake(413.52, 161.4) controlPoint1: CGPointMake(412.94, 160.69) controlPoint2: CGPointMake(413.1, 161.07)];
            [bezier14Path addCurveToPoint: CGPointMake(414.39, 162.09) controlPoint1: CGPointMake(413.81, 161.63) controlPoint2: CGPointMake(414.1, 161.86)];
            [bezier14Path addCurveToPoint: CGPointMake(420.49, 167.28) controlPoint1: CGPointMake(416.21, 164.03) controlPoint2: CGPointMake(418.48, 165.67)];
            [bezier14Path addCurveToPoint: CGPointMake(429.01, 173.66) controlPoint1: CGPointMake(423.26, 169.5) controlPoint2: CGPointMake(426.12, 171.6)];
            [bezier14Path addCurveToPoint: CGPointMake(431.06, 171.02) controlPoint1: CGPointMake(430.55, 174.76) controlPoint2: CGPointMake(432.56, 172.21)];
            [bezier14Path closePath];
            [fillColor3 setFill];
            [bezier14Path fill];


            //// Bezier 15 Drawing
            UIBezierPath* bezier15Path = UIBezierPath.bezierPath;
            [bezier15Path moveToPoint: CGPointMake(426.68, 133.66)];
            [bezier15Path addCurveToPoint: CGPointMake(414.66, 121.12) controlPoint1: CGPointMake(425.97, 127.05) controlPoint2: CGPointMake(420.81, 121.66)];
            [bezier15Path addCurveToPoint: CGPointMake(408.83, 104.12) controlPoint1: CGPointMake(416.49, 115.03) controlPoint2: CGPointMake(414.37, 107.85)];
            [bezier15Path addCurveToPoint: CGPointMake(388.44, 107.1) controlPoint1: CGPointMake(402.4, 99.79) controlPoint2: CGPointMake(393.56, 101.73)];
            [bezier15Path addCurveToPoint: CGPointMake(376, 101.67) controlPoint1: CGPointMake(385.56, 103.45) controlPoint2: CGPointMake(380.76, 101.36)];
            [bezier15Path addCurveToPoint: CGPointMake(363.35, 108.61) controlPoint1: CGPointMake(370.89, 102.01) controlPoint2: CGPointMake(366.55, 104.81)];
            [bezier15Path addCurveToPoint: CGPointMake(360.89, 102.83) controlPoint1: CGPointMake(363.37, 106.49) controlPoint2: CGPointMake(362.67, 104.45)];
            [bezier15Path addCurveToPoint: CGPointMake(353.07, 101.36) controlPoint1: CGPointMake(358.77, 100.92) controlPoint2: CGPointMake(355.64, 100.37)];
            [bezier15Path addCurveToPoint: CGPointMake(341.39, 98.02) controlPoint1: CGPointMake(350.46, 97.89) controlPoint2: CGPointMake(345.65, 96.3)];
            [bezier15Path addCurveToPoint: CGPointMake(335.15, 109.64) controlPoint1: CGPointMake(336.77, 99.88) controlPoint2: CGPointMake(334.57, 104.94)];
            [bezier15Path addCurveToPoint: CGPointMake(329.32, 120.39) controlPoint1: CGPointMake(330.9, 110.95) controlPoint2: CGPointMake(328.09, 115.97)];
            [bezier15Path addCurveToPoint: CGPointMake(339.58, 127.14) controlPoint1: CGPointMake(330.58, 124.88) controlPoint2: CGPointMake(335.15, 127.22)];
            [bezier15Path addCurveToPoint: CGPointMake(345.9, 137.49) controlPoint1: CGPointMake(339.21, 131.64) controlPoint2: CGPointMake(341.85, 135.78)];
            [bezier15Path addCurveToPoint: CGPointMake(345.32, 159.42) controlPoint1: CGPointMake(341.18, 143.52) controlPoint2: CGPointMake(341.18, 153)];
            [bezier15Path addCurveToPoint: CGPointMake(365.45, 164.02) controlPoint1: CGPointMake(349.68, 166.19) controlPoint2: CGPointMake(359.26, 168.71)];
            [bezier15Path addCurveToPoint: CGPointMake(372.84, 170.21) controlPoint1: CGPointMake(367.01, 166.95) controlPoint2: CGPointMake(369.53, 169.33)];
            [bezier15Path addCurveToPoint: CGPointMake(382, 168.17) controlPoint1: CGPointMake(376.05, 171.05) controlPoint2: CGPointMake(379.53, 170.23)];
            [bezier15Path addCurveToPoint: CGPointMake(406.44, 171.78) controlPoint1: CGPointMake(388.04, 174.95) controlPoint2: CGPointMake(398.28, 176.18)];
            [bezier15Path addCurveToPoint: CGPointMake(416.23, 151.39) controlPoint1: CGPointMake(413.41, 168.03) controlPoint2: CGPointMake(418.88, 159.1)];
            [bezier15Path addCurveToPoint: CGPointMake(426.68, 133.66) controlPoint1: CGPointMake(423.26, 149.16) controlPoint2: CGPointMake(427.46, 140.92)];
            [bezier15Path closePath];
            [fillColor2 setFill];
            [bezier15Path fill];


            //// Bezier 16 Drawing
            UIBezierPath* bezier16Path = UIBezierPath.bezierPath;
            [bezier16Path moveToPoint: CGPointMake(347.45, 127.72)];
            [bezier16Path addCurveToPoint: CGPointMake(344.52, 124.38) controlPoint1: CGPointMake(345.49, 127.71) controlPoint2: CGPointMake(344.35, 126.23)];
            [bezier16Path addCurveToPoint: CGPointMake(344.49, 124.12) controlPoint1: CGPointMake(344.52, 124.29) controlPoint2: CGPointMake(344.51, 124.2)];
            [bezier16Path addCurveToPoint: CGPointMake(344.87, 123.4) controlPoint1: CGPointMake(344.68, 123.92) controlPoint2: CGPointMake(344.82, 123.69)];
            [bezier16Path addCurveToPoint: CGPointMake(344.87, 123.01) controlPoint1: CGPointMake(344.89, 123.26) controlPoint2: CGPointMake(344.89, 123.13)];
            [bezier16Path addCurveToPoint: CGPointMake(344.92, 122.91) controlPoint1: CGPointMake(344.89, 122.98) controlPoint2: CGPointMake(344.9, 122.94)];
            [bezier16Path addCurveToPoint: CGPointMake(343.97, 121.97) controlPoint1: CGPointMake(345.28, 122.36) controlPoint2: CGPointMake(344.54, 121.54)];
            [bezier16Path addCurveToPoint: CGPointMake(343.67, 122.23) controlPoint1: CGPointMake(343.87, 122.05) controlPoint2: CGPointMake(343.77, 122.14)];
            [bezier16Path addCurveToPoint: CGPointMake(341.49, 122.4) controlPoint1: CGPointMake(342.95, 122.28) controlPoint2: CGPointMake(342.23, 122.73)];
            [bezier16Path addCurveToPoint: CGPointMake(340.65, 120.58) controlPoint1: CGPointMake(340.82, 122.11) controlPoint2: CGPointMake(340.44, 121.27)];
            [bezier16Path addCurveToPoint: CGPointMake(339.77, 119.6) controlPoint1: CGPointMake(340.85, 119.93) controlPoint2: CGPointMake(340.3, 119.54)];
            [bezier16Path addCurveToPoint: CGPointMake(338.86, 119.64) controlPoint1: CGPointMake(339.5, 119.48) controlPoint2: CGPointMake(339.18, 119.48)];
            [bezier16Path addCurveToPoint: CGPointMake(336.17, 121.52) controlPoint1: CGPointMake(337.85, 120.15) controlPoint2: CGPointMake(337.66, 121.87)];
            [bezier16Path addCurveToPoint: CGPointMake(334.76, 118.86) controlPoint1: CGPointMake(335.04, 121.26) controlPoint2: CGPointMake(334.77, 119.82)];
            [bezier16Path addCurveToPoint: CGPointMake(333.55, 118.22) controlPoint1: CGPointMake(334.74, 118.26) controlPoint2: CGPointMake(334.03, 117.89)];
            [bezier16Path addCurveToPoint: CGPointMake(332.62, 118.61) controlPoint1: CGPointMake(333.2, 118.18) controlPoint2: CGPointMake(332.83, 118.33)];
            [bezier16Path addCurveToPoint: CGPointMake(331.43, 138.54) controlPoint1: CGPointMake(326.97, 122.38) controlPoint2: CGPointMake(325.23, 134.58)];
            [bezier16Path addCurveToPoint: CGPointMake(348.58, 129.19) controlPoint1: CGPointMake(338.23, 142.88) controlPoint2: CGPointMake(346.66, 135.38)];
            [bezier16Path addCurveToPoint: CGPointMake(347.45, 127.72) controlPoint1: CGPointMake(348.8, 128.46) controlPoint2: CGPointMake(348.19, 127.73)];
            [bezier16Path closePath];
            [fillColor3 setFill];
            [bezier16Path fill];


            //// Bezier 17 Drawing
            UIBezierPath* bezier17Path = UIBezierPath.bezierPath;
            [bezier17Path moveToPoint: CGPointMake(355.72, 112.44)];
            [bezier17Path addCurveToPoint: CGPointMake(347.18, 114.85) controlPoint1: CGPointMake(352.61, 111.85) controlPoint2: CGPointMake(349.54, 112.8)];
            [bezier17Path addCurveToPoint: CGPointMake(346.96, 116) controlPoint1: CGPointMake(346.81, 115.16) controlPoint2: CGPointMake(346.79, 115.62)];
            [bezier17Path addCurveToPoint: CGPointMake(347.06, 116.32) controlPoint1: CGPointMake(346.96, 116.11) controlPoint2: CGPointMake(346.98, 116.22)];
            [bezier17Path addCurveToPoint: CGPointMake(355.2, 120.94) controlPoint1: CGPointMake(348.97, 118.79) controlPoint2: CGPointMake(352.01, 120.69)];
            [bezier17Path addCurveToPoint: CGPointMake(360.69, 117.1) controlPoint1: CGPointMake(357.71, 121.13) controlPoint2: CGPointMake(360.37, 119.83)];
            [bezier17Path addCurveToPoint: CGPointMake(355.72, 112.44) controlPoint1: CGPointMake(361.02, 114.29) controlPoint2: CGPointMake(358.06, 112.88)];
            [bezier17Path closePath];
            [fillColor3 setFill];
            [bezier17Path fill];


            //// Bezier 18 Drawing
            UIBezierPath* bezier18Path = UIBezierPath.bezierPath;
            [bezier18Path moveToPoint: CGPointMake(335.87, 124.03)];
            [bezier18Path addCurveToPoint: CGPointMake(334.24, 122.87) controlPoint1: CGPointMake(335.6, 123.34) controlPoint2: CGPointMake(334.98, 122.91)];
            [bezier18Path addCurveToPoint: CGPointMake(332.79, 125.67) controlPoint1: CGPointMake(332.75, 122.79) controlPoint2: CGPointMake(331.54, 124.53)];
            [bezier18Path addCurveToPoint: CGPointMake(333.38, 125.21) controlPoint1: CGPointMake(333.09, 125.95) controlPoint2: CGPointMake(333.64, 125.59)];
            [bezier18Path addCurveToPoint: CGPointMake(334.33, 123.55) controlPoint1: CGPointMake(332.89, 124.49) controlPoint2: CGPointMake(333.3, 123.26)];
            [bezier18Path addCurveToPoint: CGPointMake(335.12, 124.44) controlPoint1: CGPointMake(334.74, 123.66) controlPoint2: CGPointMake(335.05, 124.02)];
            [bezier18Path addCurveToPoint: CGPointMake(334.98, 125.69) controlPoint1: CGPointMake(335.21, 124.89) controlPoint2: CGPointMake(334.87, 125.26)];
            [bezier18Path addCurveToPoint: CGPointMake(335.43, 125.94) controlPoint1: CGPointMake(335.03, 125.88) controlPoint2: CGPointMake(335.24, 126)];
            [bezier18Path addCurveToPoint: CGPointMake(335.87, 124.03) controlPoint1: CGPointMake(336.14, 125.73) controlPoint2: CGPointMake(336.08, 124.58)];
            [bezier18Path closePath];
            [fillColor4 setFill];
            [bezier18Path fill];
        }


        //// Bezier 19 Drawing
        UIBezierPath* bezier19Path = UIBezierPath.bezierPath;
        [bezier19Path moveToPoint: CGPointMake(261.69, 141.89)];
        [bezier19Path addCurveToPoint: CGPointMake(248.46, 141.23) controlPoint1: CGPointMake(257.42, 139.82) controlPoint2: CGPointMake(252.87, 140.13)];
        [bezier19Path addCurveToPoint: CGPointMake(243.73, 131.89) controlPoint1: CGPointMake(248.48, 137.61) controlPoint2: CGPointMake(246.9, 134.04)];
        [bezier19Path addCurveToPoint: CGPointMake(231.73, 131.73) controlPoint1: CGPointMake(240.15, 129.45) controlPoint2: CGPointMake(235.36, 129.57)];
        [bezier19Path addCurveToPoint: CGPointMake(215.52, 120.73) controlPoint1: CGPointMake(228.35, 125.74) controlPoint2: CGPointMake(222.67, 120.96)];
        [bezier19Path addCurveToPoint: CGPointMake(200.91, 129.94) controlPoint1: CGPointMake(209.25, 120.52) controlPoint2: CGPointMake(203.32, 124.34)];
        [bezier19Path addCurveToPoint: CGPointMake(194.53, 129.31) controlPoint1: CGPointMake(198.94, 128.97) controlPoint2: CGPointMake(196.76, 128.58)];
        [bezier19Path addCurveToPoint: CGPointMake(189.89, 134.29) controlPoint1: CGPointMake(192.05, 130.13) controlPoint2: CGPointMake(190.45, 132.01)];
        [bezier19Path addCurveToPoint: CGPointMake(180.39, 135.87) controlPoint1: CGPointMake(186.87, 132.88) controlPoint2: CGPointMake(183, 133.31)];
        [bezier19Path addCurveToPoint: CGPointMake(179.8, 148.26) controlPoint1: CGPointMake(176.89, 139.29) controlPoint2: CGPointMake(177.26, 144.52)];
        [bezier19Path addCurveToPoint: CGPointMake(172.78, 164.52) controlPoint1: CGPointMake(174.25, 151.45) controlPoint2: CGPointMake(170.58, 158.08)];
        [bezier19Path addCurveToPoint: CGPointMake(186.37, 173.03) controlPoint1: CGPointMake(174.74, 170.24) controlPoint2: CGPointMake(180.67, 173.7)];
        [bezier19Path addCurveToPoint: CGPointMake(198.82, 185.31) controlPoint1: CGPointMake(187.44, 179.2) controlPoint2: CGPointMake(192.47, 184.52)];
        [bezier19Path addCurveToPoint: CGPointMake(213.09, 177.97) controlPoint1: CGPointMake(204.55, 186.02) controlPoint2: CGPointMake(210.2, 182.83)];
        [bezier19Path addCurveToPoint: CGPointMake(219.72, 180.15) controlPoint1: CGPointMake(214.92, 179.44) controlPoint2: CGPointMake(217.19, 180.3)];
        [bezier19Path addCurveToPoint: CGPointMake(226.76, 176.51) controlPoint1: CGPointMake(222.51, 179.98) controlPoint2: CGPointMake(225.02, 178.58)];
        [bezier19Path addCurveToPoint: CGPointMake(243.67, 182.08) controlPoint1: CGPointMake(231.01, 181.24) controlPoint2: CGPointMake(237.2, 184.1)];
        [bezier19Path addCurveToPoint: CGPointMake(252.45, 168.82) controlPoint1: CGPointMake(249.36, 180.31) controlPoint2: CGPointMake(253.23, 174.47)];
        [bezier19Path addCurveToPoint: CGPointMake(268.52, 154.85) controlPoint1: CGPointMake(260.22, 168.77) controlPoint2: CGPointMake(267.67, 163.05)];
        [bezier19Path addCurveToPoint: CGPointMake(261.69, 141.89) controlPoint1: CGPointMake(269.07, 149.53) controlPoint2: CGPointMake(266.57, 144.24)];
        [bezier19Path closePath];
        [fillColor2 setFill];
        [bezier19Path fill];


        //// Bezier 20 Drawing
        UIBezierPath* bezier20Path = UIBezierPath.bezierPath;
        [bezier20Path moveToPoint: CGPointMake(283.56, 45.23)];
        [bezier20Path addCurveToPoint: CGPointMake(273.82, 44.75) controlPoint1: CGPointMake(280.42, 43.71) controlPoint2: CGPointMake(277.07, 43.94)];
        [bezier20Path addCurveToPoint: CGPointMake(270.34, 37.87) controlPoint1: CGPointMake(273.83, 42.09) controlPoint2: CGPointMake(272.67, 39.46)];
        [bezier20Path addCurveToPoint: CGPointMake(261.5, 37.76) controlPoint1: CGPointMake(267.7, 36.08) controlPoint2: CGPointMake(264.17, 36.17)];
        [bezier20Path addCurveToPoint: CGPointMake(249.56, 29.66) controlPoint1: CGPointMake(259.01, 33.35) controlPoint2: CGPointMake(254.82, 29.84)];
        [bezier20Path addCurveToPoint: CGPointMake(238.81, 36.44) controlPoint1: CGPointMake(244.94, 29.5) controlPoint2: CGPointMake(240.58, 32.32)];
        [bezier20Path addCurveToPoint: CGPointMake(234.1, 35.98) controlPoint1: CGPointMake(237.35, 35.73) controlPoint2: CGPointMake(235.74, 35.44)];
        [bezier20Path addCurveToPoint: CGPointMake(230.68, 39.64) controlPoint1: CGPointMake(232.28, 36.58) controlPoint2: CGPointMake(231.1, 37.97)];
        [bezier20Path addCurveToPoint: CGPointMake(223.69, 40.81) controlPoint1: CGPointMake(228.47, 38.61) controlPoint2: CGPointMake(225.62, 38.92)];
        [bezier20Path addCurveToPoint: CGPointMake(223.25, 49.93) controlPoint1: CGPointMake(221.11, 43.32) controlPoint2: CGPointMake(221.39, 47.17)];
        [bezier20Path addCurveToPoint: CGPointMake(218.09, 61.89) controlPoint1: CGPointMake(219.17, 52.27) controlPoint2: CGPointMake(216.47, 57.15)];
        [bezier20Path addCurveToPoint: CGPointMake(228.1, 68.15) controlPoint1: CGPointMake(219.53, 66.1) controlPoint2: CGPointMake(223.9, 68.65)];
        [bezier20Path addCurveToPoint: CGPointMake(237.26, 77.19) controlPoint1: CGPointMake(228.88, 72.7) controlPoint2: CGPointMake(232.59, 76.62)];
        [bezier20Path addCurveToPoint: CGPointMake(247.77, 71.79) controlPoint1: CGPointMake(241.48, 77.72) controlPoint2: CGPointMake(245.65, 75.37)];
        [bezier20Path addCurveToPoint: CGPointMake(252.65, 73.39) controlPoint1: CGPointMake(249.12, 72.88) controlPoint2: CGPointMake(250.79, 73.5)];
        [bezier20Path addCurveToPoint: CGPointMake(257.84, 70.72) controlPoint1: CGPointMake(254.71, 73.27) controlPoint2: CGPointMake(256.56, 72.24)];
        [bezier20Path addCurveToPoint: CGPointMake(270.29, 74.82) controlPoint1: CGPointMake(260.97, 74.2) controlPoint2: CGPointMake(265.52, 76.3)];
        [bezier20Path addCurveToPoint: CGPointMake(276.75, 65.06) controlPoint1: CGPointMake(274.48, 73.51) controlPoint2: CGPointMake(277.33, 69.21)];
        [bezier20Path addCurveToPoint: CGPointMake(288.59, 54.77) controlPoint1: CGPointMake(282.48, 65.02) controlPoint2: CGPointMake(287.97, 60.81)];
        [bezier20Path addCurveToPoint: CGPointMake(283.56, 45.23) controlPoint1: CGPointMake(288.99, 50.86) controlPoint2: CGPointMake(287.16, 46.97)];
        [bezier20Path closePath];
        [fillColor2 setFill];
        [bezier20Path fill];


        //// Bezier 21 Drawing
        UIBezierPath* bezier21Path = UIBezierPath.bezierPath;
        [bezier21Path moveToPoint: CGPointMake(65.95, 15.58)];
        [bezier21Path addCurveToPoint: CGPointMake(56.21, 15.1) controlPoint1: CGPointMake(62.81, 14.06) controlPoint2: CGPointMake(59.46, 14.29)];
        [bezier21Path addCurveToPoint: CGPointMake(52.73, 8.22) controlPoint1: CGPointMake(56.22, 12.43) controlPoint2: CGPointMake(55.06, 9.81)];
        [bezier21Path addCurveToPoint: CGPointMake(43.89, 8.1) controlPoint1: CGPointMake(50.09, 6.43) controlPoint2: CGPointMake(46.56, 6.51)];
        [bezier21Path addCurveToPoint: CGPointMake(31.95, 0.01) controlPoint1: CGPointMake(41.4, 3.7) controlPoint2: CGPointMake(37.21, 0.18)];
        [bezier21Path addCurveToPoint: CGPointMake(21.2, 6.79) controlPoint1: CGPointMake(27.33, -0.15) controlPoint2: CGPointMake(22.97, 2.66)];
        [bezier21Path addCurveToPoint: CGPointMake(16.49, 6.33) controlPoint1: CGPointMake(19.74, 6.08) controlPoint2: CGPointMake(18.13, 5.79)];
        [bezier21Path addCurveToPoint: CGPointMake(13.07, 9.99) controlPoint1: CGPointMake(14.67, 6.92) controlPoint2: CGPointMake(13.48, 8.31)];
        [bezier21Path addCurveToPoint: CGPointMake(6.08, 11.15) controlPoint1: CGPointMake(10.85, 8.95) controlPoint2: CGPointMake(8.01, 9.27)];
        [bezier21Path addCurveToPoint: CGPointMake(5.64, 20.27) controlPoint1: CGPointMake(3.5, 13.67) controlPoint2: CGPointMake(3.78, 17.52)];
        [bezier21Path addCurveToPoint: CGPointMake(0.48, 32.24) controlPoint1: CGPointMake(1.56, 22.62) controlPoint2: CGPointMake(-1.14, 27.5)];
        [bezier21Path addCurveToPoint: CGPointMake(10.48, 38.5) controlPoint1: CGPointMake(1.92, 36.45) controlPoint2: CGPointMake(6.29, 39)];
        [bezier21Path addCurveToPoint: CGPointMake(19.65, 47.54) controlPoint1: CGPointMake(11.27, 43.04) controlPoint2: CGPointMake(14.98, 46.96)];
        [bezier21Path addCurveToPoint: CGPointMake(30.16, 42.14) controlPoint1: CGPointMake(23.87, 48.06) controlPoint2: CGPointMake(28.03, 45.72)];
        [bezier21Path addCurveToPoint: CGPointMake(35.04, 43.74) controlPoint1: CGPointMake(31.51, 43.22) controlPoint2: CGPointMake(33.18, 43.85)];
        [bezier21Path addCurveToPoint: CGPointMake(40.23, 41.06) controlPoint1: CGPointMake(37.1, 43.62) controlPoint2: CGPointMake(38.95, 42.59)];
        [bezier21Path addCurveToPoint: CGPointMake(52.68, 45.17) controlPoint1: CGPointMake(43.36, 44.55) controlPoint2: CGPointMake(47.91, 46.65)];
        [bezier21Path addCurveToPoint: CGPointMake(59.14, 35.4) controlPoint1: CGPointMake(56.87, 43.86) controlPoint2: CGPointMake(59.72, 39.56)];
        [bezier21Path addCurveToPoint: CGPointMake(70.98, 25.12) controlPoint1: CGPointMake(64.87, 35.37) controlPoint2: CGPointMake(70.36, 31.16)];
        [bezier21Path addCurveToPoint: CGPointMake(65.95, 15.58) controlPoint1: CGPointMake(71.38, 21.21) controlPoint2: CGPointMake(69.55, 17.32)];
        [bezier21Path closePath];
        [fillColor2 setFill];
        [bezier21Path fill];


        CGContextEndTransparencyLayer(context);
        CGContextRestoreGState(context);
    }
}

@end



@implementation UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color2
{
    UIColor* color1 = self;

    CGFloat r1 = 0, g1 = 0, b1 = 0, a1 = 0;
    CGFloat r2 = 0, g2 = 0, b2 = 0, a2 = 0;


    [color1 getRed: &r1 green: &g1 blue: &b1 alpha: &a1];
    [color2 getRed: &r2 green: &g2 blue: &b2 alpha: &a2];

    CGFloat r = r1 * (1 - fraction) + r2 * fraction;
    CGFloat g = g1 * (1 - fraction) + g2 * fraction;
    CGFloat b = b1 * (1 - fraction) + b2 * fraction;
    CGFloat a = a1 * (1 - fraction) + a2 * fraction;

    return [UIColor colorWithRed: r green: g blue: b alpha: a];
}

@end
