//
//  TSGraphics.h
//  (null)
//
//  Created by Jordan Guggenheim on 7/20/15.
//  Copyright (c) 2015 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface TSGraphics : NSObject

// Images
+ (UIImage*)clouds2;

// Drawing Methods
+ (void)drawBiggerStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation;
+ (void)drawMediumStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation;
+ (void)drawLittleStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation;
+ (void)drawBigStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation;
+ (void)drawDayNightGradientWithCanvasSize: (CGSize)canvasSize;
+ (void)drawDayGradientWithCanvasSize: (CGSize)canvasSize;
+ (void)drawNightGradientWithCanvasSize: (CGSize)canvasSize;
+ (void)drawSheepCloudsWithFrame: (CGRect)frame;
+ (void)drawMediumCloudsWithFrame: (CGRect)frame;
+ (void)drawLightCloudsWithFrame: (CGRect)frame;
+ (void)drawHeavyRainCloudsWithFrame: (CGRect)frame;
+ (void)drawVeryLightCloudsWithFrame: (CGRect)frame;
+ (void)drawMediumCloudsRainWithFrame: (CGRect)frame;
+ (void)drawSheepCloudsRainWithFrame: (CGRect)frame;
+ (void)drawHeavyCloudsHeavyRainWithFrame: (CGRect)frame;
+ (void)drawLightSheepCloudsWithFrame: (CGRect)frame legRotation: (CGFloat)legRotation;
+ (void)drawHeavyCloudsMediumRainWithFrame: (CGRect)frame;
+ (void)drawHeavyCloudsLightRainWithFrame: (CGRect)frame;
+ (void)drawHeavyCloudsMayRainWithFrame: (CGRect)frame;
+ (void)drawHeavyCloudsWithFrame: (CGRect)frame;
+ (void)drawSunOneWithFrame: (CGRect)frame;
+ (void)drawSunTwoWithFrame: (CGRect)frame sunRotation: (CGFloat)sunRotation scale: (CGFloat)scale;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
