//
//  TSStar.m
//  (null)
//
//  Created by Jordan Guggenheim on 7/11/15.
//  Copyright (c) 2015 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "TSGraphics.h"


@implementation TSGraphics

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawBiggerStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// star Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame) + 11.12, CGRectGetMinY(frame) + 9.62);
    CGContextRotateCTM(context, -rotation * M_PI / 180);

    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(0, -9.38)];
    [starPath addLineToPoint: CGPointMake(2.5, -3.26)];
    [starPath addLineToPoint: CGPointMake(9.39, -2.9)];
    [starPath addLineToPoint: CGPointMake(4.04, 1.25)];
    [starPath addLineToPoint: CGPointMake(5.8, 7.58)];
    [starPath addLineToPoint: CGPointMake(0, 4.03)];
    [starPath addLineToPoint: CGPointMake(-5.8, 7.58)];
    [starPath addLineToPoint: CGPointMake(-4.04, 1.25)];
    [starPath addLineToPoint: CGPointMake(-9.39, -2.9)];
    [starPath addLineToPoint: CGPointMake(-2.5, -3.26)];
    [starPath closePath];
    [starColor setFill];
    [starPath fill];

    CGContextRestoreGState(context);
}

+ (void)drawMediumStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// star Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame) + 6.96, CGRectGetMinY(frame) + 6.98);
    CGContextRotateCTM(context, -rotation * M_PI / 180);

    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(0, -7.03)];
    [starPath addLineToPoint: CGPointMake(1.2, -2.07)];
    [starPath addLineToPoint: CGPointMake(6.09, -3.51)];
    [starPath addLineToPoint: CGPointMake(2.39, -0)];
    [starPath addLineToPoint: CGPointMake(6.09, 3.51)];
    [starPath addLineToPoint: CGPointMake(1.2, 2.07)];
    [starPath addLineToPoint: CGPointMake(0, 7.03)];
    [starPath addLineToPoint: CGPointMake(-1.2, 2.07)];
    [starPath addLineToPoint: CGPointMake(-6.09, 3.51)];
    [starPath addLineToPoint: CGPointMake(-2.39, -0)];
    [starPath addLineToPoint: CGPointMake(-6.09, -3.51)];
    [starPath addLineToPoint: CGPointMake(-1.2, -2.07)];
    [starPath closePath];
    [starColor setFill];
    [starPath fill];

    CGContextRestoreGState(context);
}

+ (void)drawLittleStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// star Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame) + 2, CGRectGetMinY(frame) + 2);
    CGContextRotateCTM(context, -rotation * M_PI / 180);

    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(0, -1.5)];
    [starPath addLineToPoint: CGPointMake(0.18, -0.48)];
    [starPath addLineToPoint: CGPointMake(0.99, -1.15)];
    [starPath addLineToPoint: CGPointMake(0.45, -0.25)];
    [starPath addLineToPoint: CGPointMake(1.51, -0.26)];
    [starPath addLineToPoint: CGPointMake(0.51, 0.09)];
    [starPath addLineToPoint: CGPointMake(1.33, 0.75)];
    [starPath addLineToPoint: CGPointMake(0.34, 0.39)];
    [starPath addLineToPoint: CGPointMake(0.53, 1.41)];
    [starPath addLineToPoint: CGPointMake(0, 0.51)];
    [starPath addLineToPoint: CGPointMake(-0.53, 1.41)];
    [starPath addLineToPoint: CGPointMake(-0.34, 0.39)];
    [starPath addLineToPoint: CGPointMake(-1.33, 0.75)];
    [starPath addLineToPoint: CGPointMake(-0.51, 0.09)];
    [starPath addLineToPoint: CGPointMake(-1.51, -0.26)];
    [starPath addLineToPoint: CGPointMake(-0.45, -0.25)];
    [starPath addLineToPoint: CGPointMake(-0.99, -1.15)];
    [starPath addLineToPoint: CGPointMake(-0.18, -0.48)];
    [starPath closePath];
    [starColor setFill];
    [starPath fill];

    CGContextRestoreGState(context);
}

+ (void)drawBigStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// star Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame) + 9.62, CGRectGetMinY(frame) + 8.12);
    CGContextRotateCTM(context, -rotation * M_PI / 180);

    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(0, -7.88)];
    [starPath addLineToPoint: CGPointMake(2.12, -2.74)];
    [starPath addLineToPoint: CGPointMake(7.97, -2.43)];
    [starPath addLineToPoint: CGPointMake(3.42, 1.05)];
    [starPath addLineToPoint: CGPointMake(4.92, 6.37)];
    [starPath addLineToPoint: CGPointMake(0, 3.39)];
    [starPath addLineToPoint: CGPointMake(-4.92, 6.37)];
    [starPath addLineToPoint: CGPointMake(-3.42, 1.05)];
    [starPath addLineToPoint: CGPointMake(-7.97, -2.43)];
    [starPath addLineToPoint: CGPointMake(-2.12, -2.74)];
    [starPath closePath];
    [starColor setFill];
    [starPath fill];

    CGContextRestoreGState(context);
}

+ (void)drawDayNightGradientWithCanvasSize: (CGSize)canvasSize
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* green = [UIColor colorWithRed: 0.58 green: 0.729 blue: 0.396 alpha: 1];
    UIColor* blue = [UIColor colorWithRed: 0.153 green: 0.565 blue: 0.682 alpha: 1];
    UIColor* midnight = [UIColor colorWithRed: 0 green: 0 blue: 0.039 alpha: 1];

    //// Gradient Declarations
    CGFloat gradientLocations[] = {0, 0.5, 1};
    CGGradientRef gradient = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)green.CGColor, (id)blue.CGColor, (id)midnight.CGColor], gradientLocations);

    //// backgroundGradient Drawing
    CGRect backgroundGradientRect = CGRectMake(0, 0, canvasSize.width, canvasSize.height);
    UIBezierPath* backgroundGradientPath = [UIBezierPath bezierPathWithRect: backgroundGradientRect];
    CGContextSaveGState(context);
    [backgroundGradientPath addClip];
    CGContextDrawLinearGradient(context, gradient,
        CGPointMake(CGRectGetMidX(backgroundGradientRect), CGRectGetMaxY(backgroundGradientRect)),
        CGPointMake(CGRectGetMidX(backgroundGradientRect), CGRectGetMinY(backgroundGradientRect)),
        0);
    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(gradient);
    CGColorSpaceRelease(colorSpace);
}

+ (void)drawDayGradientWithCanvasSize: (CGSize)canvasSize
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* green = [UIColor colorWithRed: 0.58 green: 0.729 blue: 0.396 alpha: 1];
    UIColor* blue = [UIColor colorWithRed: 0.153 green: 0.565 blue: 0.682 alpha: 1];

    //// Gradient Declarations
    CGFloat dayLocations[] = {0, 0.5, 1};
    CGGradientRef day = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)green.CGColor, (id)[green blendedColorWithFraction: 0.5 ofColor: blue].CGColor, (id)blue.CGColor], dayLocations);

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(0, 0, canvasSize.width, canvasSize.height);
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: rectangleRect];
    CGContextSaveGState(context);
    [rectanglePath addClip];
    CGContextDrawLinearGradient(context, day,
        CGPointMake(CGRectGetMidX(rectangleRect), CGRectGetMaxY(rectangleRect)),
        CGPointMake(CGRectGetMidX(rectangleRect), CGRectGetMinY(rectangleRect)),
        0);
    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(day);
    CGColorSpaceRelease(colorSpace);
}

+ (void)drawNightGradientWithCanvasSize: (CGSize)canvasSize
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* blue = [UIColor colorWithRed: 0.153 green: 0.565 blue: 0.682 alpha: 1];
    UIColor* midnight = [UIColor colorWithRed: 0 green: 0 blue: 0.039 alpha: 1];

    //// Gradient Declarations
    CGFloat nIghtLocations[] = {0, 0.76};
    CGGradientRef nIght = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)blue.CGColor, (id)midnight.CGColor], nIghtLocations);

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(0, 0, canvasSize.width, canvasSize.height);
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: rectangleRect];
    CGContextSaveGState(context);
    [rectanglePath addClip];
    CGContextDrawLinearGradient(context, nIght,
        CGPointMake(CGRectGetMidX(rectangleRect), CGRectGetMaxY(rectangleRect)),
        CGPointMake(CGRectGetMidX(rectangleRect), CGRectGetMinY(rectangleRect)),
        0);
    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(nIght);
    CGColorSpaceRelease(colorSpace);
}

@end



@implementation UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color2
{
    UIColor* color1 = self;

    CGFloat r1 = 0, g1 = 0, b1 = 0, a1 = 0;
    CGFloat r2 = 0, g2 = 0, b2 = 0, a2 = 0;


    [color1 getRed: &r1 green: &g1 blue: &b1 alpha: &a1];
    [color2 getRed: &r2 green: &g2 blue: &b2 alpha: &a2];

    CGFloat r = r1 * (1 - fraction) + r2 * fraction;
    CGFloat g = g1 * (1 - fraction) + g2 * fraction;
    CGFloat b = b1 * (1 - fraction) + b2 * fraction;
    CGFloat a = a1 * (1 - fraction) + a2 * fraction;

    return [UIColor colorWithRed: r green: g blue: b alpha: a];
}

@end
