//
//  TSStar.m
//  (null)
//
//  Created by Jordan Guggenheim on 6/27/15.
//  Copyright (c) 2015 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "TSStar.h"


@implementation TSStar

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawBigStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// star Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame) + 13, CGRectGetMinY(frame) + 13);
    CGContextRotateCTM(context, -rotation * M_PI / 180);

    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(0, -12.5)];
    [starPath addLineToPoint: CGPointMake(3.31, -4.55)];
    [starPath addLineToPoint: CGPointMake(11.89, -3.86)];
    [starPath addLineToPoint: CGPointMake(5.35, 1.74)];
    [starPath addLineToPoint: CGPointMake(7.35, 10.11)];
    [starPath addLineToPoint: CGPointMake(0, 5.62)];
    [starPath addLineToPoint: CGPointMake(-7.35, 10.11)];
    [starPath addLineToPoint: CGPointMake(-5.35, 1.74)];
    [starPath addLineToPoint: CGPointMake(-11.89, -3.86)];
    [starPath addLineToPoint: CGPointMake(-3.31, -4.55)];
    [starPath closePath];
    [starColor setFill];
    [starPath fill];

    CGContextRestoreGState(context);
}

+ (void)drawLittleStarWithFrame: (CGRect)frame starColor: (UIColor*)starColor rotation: (CGFloat)rotation
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// star Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, CGRectGetMinX(frame) + 6.96, CGRectGetMinY(frame) + 6.98);
    CGContextRotateCTM(context, -rotation * M_PI / 180);

    UIBezierPath* starPath = UIBezierPath.bezierPath;
    [starPath moveToPoint: CGPointMake(0, -7.03)];
    [starPath addLineToPoint: CGPointMake(1.2, -2.07)];
    [starPath addLineToPoint: CGPointMake(6.09, -3.51)];
    [starPath addLineToPoint: CGPointMake(2.39, -0)];
    [starPath addLineToPoint: CGPointMake(6.09, 3.51)];
    [starPath addLineToPoint: CGPointMake(1.2, 2.07)];
    [starPath addLineToPoint: CGPointMake(0, 7.03)];
    [starPath addLineToPoint: CGPointMake(-1.2, 2.07)];
    [starPath addLineToPoint: CGPointMake(-6.09, 3.51)];
    [starPath addLineToPoint: CGPointMake(-2.39, -0)];
    [starPath addLineToPoint: CGPointMake(-6.09, -3.51)];
    [starPath addLineToPoint: CGPointMake(-1.2, -2.07)];
    [starPath closePath];
    [starColor setFill];
    [starPath fill];

    CGContextRestoreGState(context);
}

@end
